// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Birth  int    `json:"birth"`
}

type Mutation struct {
}

type NewAuthor struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Birth  int    `json:"birth"`
}

type NewItem struct {
	UserID string   `json:"user_id"`
	Title  string   `json:"title"`
	Image  string   `json:"image"`
	Status string   `json:"status"`
	Author string   `json:"author"`
	Tags   []string `json:"tags,omitempty"`
	Date   string   `json:"date"`
}

type NewReview struct {
	Reviewer string `json:"reviewer"`
	Item     string `json:"item"`
	Score    int    `json:"score"`
	Comment  string `json:"comment"`
}

type NewTag struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

type Query struct {
}

type Review struct {
	ID       string `json:"id"`
	Reviewer string `json:"reviewer"`
	Item     string `json:"item"`
	Score    int    `json:"score"`
	Comment  string `json:"comment"`
}

type Tag struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}
